//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Dateposted { get; set; }
        public int AuthorId { get; set; }
        public int PosterId { get; set; }
        public string Avatar { get; set; }
        public int CategoryId { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> View { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
    }
}
